### ISSUE TITLE
aside

### ISSUE THREAD

**Issue by Elijah017** [normit581/cits3200-proj#14]
# Purpose

I believe it would be stylistically valuable to include an `<aside>` into our home page. This aside would be updated every time a document is dropped/uploaded and would have some feature to allow removing documents from being compared.

# Benefit

We should initially be focusing on comparing only two documents at once, however we should also have some consideration into how we are going to handle comparing multiple documents at once. This aside would be easily able to manage both in a very clean way.

- two documents at once: set a limit of two documents to the input but set up the aside to dynamically grow larger than that.
- multiple documents: simply remove the limit on documents and the dynamic aside will also be able to handle it

This will also provide a clean and simple way to view and access all uploaded documents. It could possibly also be extended to handle post comparison features, like going between documents to see the matching sections or displaying the documents and the percentage match in a simple table.

# Immediate Recommendation

Implement a simple aside in the layouts directory of the templates. How this will be extended can be considered more thoroughly and applied at a later date.

**Comment by loklokyx** [comment]
That sounds like a great idea! Using HTML `<aside>` tag can enhance the user experience by providing supplementary information or context without disrupting the main content. Looking forward to seeing how it’s implemented!
