### ISSUE TITLE
File Uploader Improvements - Visual Feedback, File Validation and Response Handler

### ISSUE THREAD

**Issue by jbwod** [normit581/cits3200-proj#16]
## Purpose
To add several validation and feedback functionalities to the File Uploader.
- Progress Bar: Show upload progress for each file.
- File Validation Improvements `fileSize`, `fileType` and `fileCount`
- A restriction on uploaded file to prevent misuse.
- Success/Failure feedback redesigned with an AJAX Handler for better interaction.

## Benefit
This would enhance user feedback and prevent the uploading of large files that may cause problems with the comparison and report process. Provide an indicator of progress when uploading the files so the User knows the current state of their upload. Make the uploader more robust when it gets subjected to regular use.

**Comment by loklokyx** [comment]
Great idea! I have the working code for sending files to the backend. I'll create an issue for that. After I merge it into the main branch, you can continue working on the size validation.

**Comment by jbwod** [comment]
The initial uploader has been migrated to an AJAX response handler.

We do this so the page doesn't have to reload/change routes to display new content. Instead, we now do this automatically,

**Comment by jbwod** [comment]
Progress indicators do need more work.
We can refactor this in another feature request down the track, initial state works as intended per the goals of the Issue.
- Tracking how many files (assuming the max of two for now)
- Confirmation once submitted
