### ISSUE TITLE
test cal_sim

### ISSUE THREAD

**Issue by Lu0922** [normit581/cits3200-proj#17]
Add similarity calculation between 2 .docx  to test/
similarity between <A.docx> <B.docx>:   

### Jaccard Similarity Formula

The Jaccard similarity coefficient can be calculated using the formula:

###  J(A,B)=∣A∩B∣​/∣A∪B∣

- **A** is the set of RSIDs from the first document
- **B** is the set of RSIDs from the second document
- ∣A∩B∣ is the number of common RSIDs between both sets
- ∣A∪B∣ is the total number of unique RSIDs across both sets

**Comment by normit581** [comment]
Looking good
