### ISSUE TITLE
rewrite_matching_calculation

### ISSUE THREAD

**Issue by Lu0922** [normit581/cits3200-proj#39]
# According to meeting with client
>" two documents we should just display each documents relative percentage match (docuement 1 has 100 rsid, document 2 has 200 rsid, they match 30 rsid, output is document 1: 30%, document 2: 15%) "

### revised formula
- result % will be rename as rsid_matching_result
- function will be rename as rsid_match2

matching result: 
<current .docx> to <target .docx>
result % = number of common rsid / total number of rsid in current .docx

### output format

> result_dict = {
"doc1": [("doc2", 0.35,), ("doc3", 0.15,)],
"doc2:": [("doc1", 0.5,)]
}

**Comment by Elijah017** [comment]
seems like a good idea. If you can think of a better way to output result let us know, that result dict was just a quick thought

**Comment by Lu0922** [comment]
dictionary containing a list of result is a good idea, python list are easy for sorting. 
We'll see how it work first
