### ISSUE TITLE
unittest_rsid

### ISSUE THREAD

**Issue by Lu0922** [normit581/cits3200-proj#46]
# Setup unittest according to project acceptance test :

## Test A – RSID Extraction & Detection
	Requirements
    • The program must identify and extract all RSID Codes from a given file.
    • The program must handle file conversion and extract codes from the document.xml
    • The program must not alter these Codes in any way during the extraction.

## Test B – Percentage Calculation of Common RSID Codes
	Requirements
    • The program must have at least two sets of RSID codes.
    • The program must display a percentage summary.
    • The program must be repeatable, generating the same result.

**Comment by jbwod** [comment]
Great idea - would be good to have this in a measurable output.
