### ISSUE TITLE
RSID section color on Visualise page

### ISSUE THREAD

**Issue by loklokyx** [normit581/cits3200-proj#49]
**Feature:**

Enhance the Visualise Page by allowing users to modify colours to the RSID section for both the base and compare .docx documents. Users should be able to customise their colour preferences and remove colours with a double-click.

**Implementation:**

**Colour Customisation:** Allow users to select and apply colours to the RSID section for both the base and compare documents. Implement a colour picker tool to enable easy customisation.

**Double-Click Removal:** Enable users to remove applied colours by double-clicking on the RSID section.

**UI/UX Enhancements:** Ensure the colour customisation feature is intuitive and seamlessly integrated into the Visualise Page. Provide visual feedback when colours are applied or removed to enhance user interaction.

**Comment by normit581** [comment]
Hey,

{'00363A3B': {'count': 1, 'location1': ['CITS3200 Team 11'], 'location2': ['CITS3200 Team 11']}

This is an example rsid location I've extracted where they have matching rsid, Would it be easier for you if I linked the rsid with the metadata text? or is that dict sufficient enough.

**Comment by loklokyx** [comment]
I think we can enhance the output by reusing the `meta_datalist` and appending the RSID codes into the paragraphs. This would allow us to attach CSS styles based on the RSID codes. If two documents share the same RSID, they will automatically display with the same colour for consistent visualisation across documents. Please let me know if I've misunderstood or inaccurately explained the RSID usage.

---

Additionally, I think I will implement two buttons for better visualisation (for new issue):
- Show Match RSID Button: Highlights all text with matching RSIDs across documents.
- Show Individual RSID Button: Highlights text for each unique RSID individually.

These features will improve how we present and compare document similarities.

---

Below is the `meta_datalist` example:

Current `meta_datalist`
```
[
 {
  "file_name":"doc4Student.docx",
  "metadata":{
  "title":"",
  "created":"",
  "paragraphs":["CITS3200 Team 11", "Test "]
  }
 },
 {
  "file_name":"doc3Student.docx",
  "metadata":{
  "title":"",
  "created":"",
  "paragraphs":["CITS3200 Team 11", "I am unique rsid"]
  }
 }
]
```
New `meta_datalist`
```
[
 {
  "file_name":"doc4Student.docx",
  "metadata":{
  "title":"",
  "created":"",
  "paragraphs":[
    {
     "rsid":"00363A3B",
     "text":"CITS3200 Team 11"
    },
    {
     "rsid":"23AA3A3B",
     "text":"Test "
    }
   ]
  }
 },
 {
  "file_name":"doc3Student.docx",
  "metadata":{
  "title":"",
  "created":"",
  "paragraphs":[
    {
     "rsid":"00363A3B",
     "text":"CITS3200 Team 11"
    },
    {
     "rsid":"463HA721",
     "text":"I am unique rsid"
    }
   ]
  }
 }
]
```

**Comment by normit581** [comment]
Ok yep, I'll combine the current dictionary with the metadata list.

**Comment by normit581** [comment]
This is how i've gotten it to look like:
{'rsid': ['001B1AE3'], 'text': 'Category: Project plan'} ``` Getting rid of repeated rsids.

So the start of the second way is:
comparison meta: {'title': '', 'paragraphs': [{'rsid': [], 'text': 'Risk Register '}, {'rsid': ['001B1AE3'], 'text': 'Group 11'} 

I've kept the original metadata for document display and have this comparison_metadata for comparison and highlighting.

**Comment by loklokyx** [comment]
As discussed in today's meeting, the backend will generate the colour. The estimated time for this task will be extended to next week.
