### ISSUE TITLE
RSID with spacing in matching_rsid on Visualise Route

### ISSUE THREAD

**Issue by loklokyx** [normit581/cits3200-proj#61]
In the Visualise route, the `matching_rsid ` field contains RSID with spacing. This spacing should not be present as discussed

**Steps to Reproduce:**
1. Upload the base document and compare it with the file attached.
2. Click the first element to trigger the Visualise route to match RSIDs.
3. Observe that the `matching_rsid` contains spaces between RSID.

**Expected Behavior:**
- The `matching_rsid` field suppose to have text.

**Attachments:**
- **Base file:** [doc1Student.docx](https://github.com/user-attachments/files/16914613/doc1Student.docx)
- **Compare file:** [doc2Student.docx](https://github.com/user-attachments/files/16914614/doc2Student.docx)

**Current Output:**
- `matching_rsid` = `{'00E42020': {'count': 1, 'text1': ['Test asd  this match'], 'text2': ['Test asd  this match', '']}, '008154EA': {'count': 1, 'text1': ['Test asd  this match'], 'text2': ['Test asd  this match']}}`
- `rsid_metadata` = `{'title': '', 'paragraphs': [{'rsid': '00E42020', 'text': 'Test asd  this match'}, {'rsid': '008154EA', 'text': 'Test asd  this match'}]}`

**Comment by normit581** [comment]
I think thats normal due to the rsid counting the revision of a space. What we can do is in the comparison_meta which includes the colouring I can iterate through and if the text is ' ' then dont add it.
