### ISSUE TITLE
Skills and Resources Audit

### ISSUE THREAD

**Issue by normit581** [normit581/cits3200-proj#7]
Writing the skills and resources deliverable

So far the skills I have required for this project are:

**Programming skills**
- File handling
- XML parsing
- Python

**Web development**
- Frontend (HTML, Jinja, CSS)
- Flask, SQL

**Data Analysis**

Resources required for this project so far:
**Development tools**
- IDE etc

**Libraries and frameworks**
- Flask
- Python docx
- XML libraries

**Sample documents**
- Document generator

**Documentation**
- Github, Excel spreadsheets

**Version control**
- Git

**Security**
- HTTPS
- Input validation
- CRSF
- XSS
- Error handling

Does anyone have anyone have any other Skills or resources they think would be needed for this project?

After we've gathered all Skills & resources required, then we'll see what the team has versus what is required for the project and compare.

**Comment by loklokyx** [comment]
Hi @normit581, I noticed that the tester part seems to be missing. Some of the required testing skills might include:
- User Acceptance Testing
- System Testing
- Functional Testing
- Integration Testing
- Unit Testing
- Performance testing
